"""Added stuff to Run model

Revision ID: 0f42c54003a6
Revises: 
Create Date: 2025-07-28 15:51:10.750783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f42c54003a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('run', schema=None) as batch_op:
        batch_op.add_column(sa.Column('strava_activity_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('average_cadence', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('average_speed', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('average_heartrate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_elevation_gain', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('kudos_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('elapsed_time', sa.Integer(), nullable=True))
        batch_op.alter_column('pace_min_per_km',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.create_unique_constraint('uq_run_strava_activity_id', ['strava_activity_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('run', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('pace_min_per_km',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.drop_column('elapsed_time')
        batch_op.drop_column('kudos_count')
        batch_op.drop_column('name')
        batch_op.drop_column('total_elevation_gain')
        batch_op.drop_column('average_heartrate')
        batch_op.drop_column('average_speed')
        batch_op.drop_column('average_cadence')
        batch_op.drop_column('strava_activity_id')

    # ### end Alembic commands ###
